version: "3.7"

services:
  golang-api-postgres:
    image: postgres
    container_name: golang-api-postgres
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/golang-api
    volumes:
      - golang-api:/var/lib/postgresql/data

volumes:
  golang-api: